CREATE TABLE IF NOT EXISTS `Recept` (
	`ReceptID` INTEGER NOT NULL AUTO_INCREMENT,
	`Nev` VARCHAR(150) NOT NULL,
	`Kep` VARCHAR(255) NOT NULL,
	`ElkeszitesiIdo` TIME NOT NULL,
	`NehezsegiSzintID` INTEGER NOT NULL,
	`BegyujthetoPontok` INTEGER NOT NULL,
	`Adag` INTEGER NOT NULL,
	`Elkeszitesi_leiras` TEXT NOT NULL,
	`ElkeszitesiModID` INTEGER NOT NULL,
	`Koltseg` INTEGER NOT NULL,
	`AlkategoriaID` INTEGER NOT NULL,
	`ArkategoriaID` INTEGER NOT NULL,
	`Kaloria` DECIMAL(6,2) NOT NULL,
	PRIMARY KEY(`ReceptID`)
);


CREATE TABLE IF NOT EXISTS `Hozzavalo` (
	`HozzavaloID` INTEGER NOT NULL AUTO_INCREMENT,
	`Elnevezes` VARCHAR(50) NOT NULL,
	`Kep` VARCHAR(255),
	PRIMARY KEY(`HozzavaloID`)
);


CREATE TABLE IF NOT EXISTS `Recept_Hozzavalo` (
	`ReceptID` INTEGER NOT NULL,
	`HozzavaloID` INTEGER NOT NULL,
	`Mennyiseg` DECIMAL(10,2) NOT NULL,
	`MertekegysegID` INTEGER NOT NULL,
	PRIMARY KEY(`ReceptID`, `HozzavaloID`)
);


CREATE TABLE IF NOT EXISTS `KonyhaiFelszereles` (
	`KonyhaiFelszerelesID` INTEGER NOT NULL AUTO_INCREMENT,
	`Nev` VARCHAR(100) NOT NULL,
	`Kep` VARCHAR(255),
	`BesorolasID` INTEGER NOT NULL,
	`Leiras` TEXT NOT NULL,
	PRIMARY KEY(`KonyhaiFelszerelesID`)
);


CREATE TABLE IF NOT EXISTS `Recept_KonyhaiFelszereles` (
	`ReceptID` INTEGER NOT NULL,
	`KonyhaiFelszerelesID` INTEGER NOT NULL,
	PRIMARY KEY(`ReceptID`, `KonyhaiFelszerelesID`)
);


CREATE TABLE IF NOT EXISTS `Felhasznalo` (
	`FelhasznaloID` INTEGER NOT NULL AUTO_INCREMENT,
	`Vezeteknev` VARCHAR(50) NOT NULL,
	`Keresztnev` VARCHAR(50) NOT NULL,
	`Felhasznalonev` VARCHAR(30) NOT NULL,
	`Emailcim` VARCHAR(254) NOT NULL,
	`Jelszo` VARCHAR(255) NOT NULL,
	`SzuletesiEv` YEAR NOT NULL,
	`Profilkep` VARCHAR(255) NOT NULL,
	`OrszagID` INTEGER NOT NULL,
	`RegisztracioEve` YEAR NOT NULL,
	`MegszerzettPontok` INTEGER NOT NULL,
	`SzerepID` INTEGER,
	PRIMARY KEY(`FelhasznaloID`)
);


CREATE TABLE IF NOT EXISTS `Felhasznalo_Recept` (
	`FelhasznaloID` INTEGER NOT NULL,
	`ReceptID` INTEGER NOT NULL,
	`Elkeszitette` BOOLEAN,
	`KedvencReceptek` BOOLEAN,
	PRIMARY KEY(`FelhasznaloID`, `ReceptID`)
);


CREATE TABLE IF NOT EXISTS `Felhasznalo_Hozzavalo` (
	`FelhasznaloID` INTEGER NOT NULL,
	`HozzavaloID` INTEGER NOT NULL,
	`Mennyiseg` DECIMAL(10,2) NOT NULL,
	`MertekegysegID` INTEGER NOT NULL,
	PRIMARY KEY(`FelhasznaloID`, `HozzavaloID`)
) COMMENT='Hűtő';


CREATE TABLE IF NOT EXISTS `NehezsegiSzint` (
	`NehezsegiSzintID` INTEGER NOT NULL AUTO_INCREMENT,
	`Szint` INTEGER NOT NULL,
	PRIMARY KEY(`NehezsegiSzintID`)
);


CREATE TABLE IF NOT EXISTS `Kategoria` (
	`KategoriaID` INTEGER NOT NULL AUTO_INCREMENT,
	`Kategoria` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`KategoriaID`)
);


CREATE TABLE IF NOT EXISTS `Alkategoria` (
	`AlkategoriaID` INTEGER NOT NULL AUTO_INCREMENT,
	`KategoriaID` INTEGER NOT NULL,
	`Alkategoria` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`AlkategoriaID`)
);


CREATE TABLE IF NOT EXISTS `Mertekegyseg` (
	`MertekegysegID` INTEGER NOT NULL AUTO_INCREMENT,
	`Elnevezes` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`MertekegysegID`)
);


CREATE TABLE IF NOT EXISTS `Orszag` (
	`OrszagID` INTEGER NOT NULL AUTO_INCREMENT,
	`Elnevezes` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`OrszagID`)
);


CREATE TABLE IF NOT EXISTS `ElkeszitesiMod` (
	`ElkeszitesiModID` INTEGER NOT NULL AUTO_INCREMENT,
	`ElkeszitesiMod` VARCHAR(255) NOT NULL,
	`Hofok` INTEGER,
	`Funkcio` VARCHAR(50),
	PRIMARY KEY(`ElkeszitesiModID`)
);


CREATE TABLE IF NOT EXISTS `Besorolas` (
	`BesorolasID` INTEGER NOT NULL AUTO_INCREMENT,
	`Elnevezes` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`BesorolasID`)
);


CREATE TABLE IF NOT EXISTS `Szerep` (
	`SzerepID` INTEGER NOT NULL AUTO_INCREMENT,
	`Szerep` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`SzerepID`)
);


CREATE TABLE IF NOT EXISTS `Arkategoria` (
	`ArkategoriaID` INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
	`Arkategoria` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`ArkategoriaID`)
);


ALTER TABLE `Recept`
ADD FOREIGN KEY(`NehezsegiSzintID`) REFERENCES `NehezsegiSzint`(`NehezsegiSzintID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Recept`
ADD FOREIGN KEY(`ElkeszitesiModID`) REFERENCES `ElkeszitesiMod`(`ElkeszitesiModID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Recept`
ADD FOREIGN KEY(`AlkategoriaID`) REFERENCES `Alkategoria`(`AlkategoriaID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Alkategoria`
ADD FOREIGN KEY(`KategoriaID`) REFERENCES `Kategoria`(`KategoriaID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `KonyhaiFelszereles`
ADD FOREIGN KEY(`BesorolasID`) REFERENCES `Besorolas`(`BesorolasID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Felhasznalo`
ADD FOREIGN KEY(`OrszagID`) REFERENCES `Orszag`(`OrszagID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Felhasznalo`
ADD FOREIGN KEY(`SzerepID`) REFERENCES `Szerep`(`SzerepID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Recept_Hozzavalo`
ADD FOREIGN KEY(`ReceptID`) REFERENCES `Recept`(`ReceptID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Recept_Hozzavalo`
ADD FOREIGN KEY(`HozzavaloID`) REFERENCES `Hozzavalo`(`HozzavaloID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Recept_Hozzavalo`
ADD FOREIGN KEY(`MertekegysegID`) REFERENCES `Mertekegyseg`(`MertekegysegID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Recept_KonyhaiFelszereles`
ADD FOREIGN KEY(`ReceptID`) REFERENCES `Recept`(`ReceptID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Recept_KonyhaiFelszereles`
ADD FOREIGN KEY(`KonyhaiFelszerelesID`) REFERENCES `KonyhaiFelszereles`(`KonyhaiFelszerelesID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Felhasznalo_Recept`
ADD FOREIGN KEY(`FelhasznaloID`) REFERENCES `Felhasznalo`(`FelhasznaloID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Felhasznalo_Recept`
ADD FOREIGN KEY(`ReceptID`) REFERENCES `Recept`(`ReceptID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Felhasznalo_Hozzavalo`
ADD FOREIGN KEY(`FelhasznaloID`) REFERENCES `Felhasznalo`(`FelhasznaloID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Felhasznalo_Hozzavalo`
ADD FOREIGN KEY(`HozzavaloID`) REFERENCES `Hozzavalo`(`HozzavaloID`)
ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE `Recept`
ADD FOREIGN KEY(`ArkategoriaID`) REFERENCES `Arkategoria`(`ArkategoriaID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;